server:
    port: 1018

spring:
    application:
        name: mobile-proxy   
    datasource:
#        localhost
#        url: ENC(YdU8jCaiJ+r3CXw3YEEm4JGJ7ht1X9/PykIr0d9JhHhac0YrKxFOgs6RkA378zhzbrdWXTJSXY40js/uCCidkzJ8dZJr/lUz)
#        .32
        
        url:  jdbc:sqlserver://192.168.1.37;databaseName=omnix;encrypt=true;trustServerCertificate=true;    
        username:  ENC(6tnkBZmV7hyJESIdrgMIWA==)
        password: ENC(LR+qQ9W1kzbii+Xb7S4fZxGnvl2ZzzcK)
        driver-class-name:  com.microsoft.sqlserver.jdbc.SQLServerDriver
        initialization-mode: always
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.SQLServer2012Dialect
            ddl-auto: update
            show-sql: true
    thymeleaf:
        cache: false
security:
    pgp:
        encryption:
            userId: ENC(mbWeJaB9OUJvG7b1UobXdtlB5gix+uAsO3VvrdJuw4c=)
            password: ENC(XTxipOSAIy/7lpDOoJZuEe5w57vhtfEh)
            privateKey: C:\\MobileProxy\\keys\\privatekey.asc
            publicKey: C:\\MobileProxy\\keys\\recipient_publickey.asc
            apPprivateKey: C:\\MobileProxy\\keys\\recipient\\recipient_privatekey.asc
            appPrivateKeyPass : ENC(XTxipOSAIy/7lpDOoJZuEe5w57vhtfEh)
    omnix:
        encryption:
            key: FLWSECK-f6be2996841f1da0dfb7e27b9a3bd5bf-X
        base-url:  https://192.168.1.7:8443/omnix/api
#        base-url:  https://localhost:8443/omnix/api
    proxy:
#        url: http://localhost:1018/proxy
        url: http://mobilebankinglive.accionmfb.com:1018/proxy
    jwt:
        signing:
            Key: j3H5Ld5nYmGWyULy6xwpOgfSH++NgKXnJMq20vpfd+8=t
    aes:
        encryption:
            key : 99T18925x42983H9508302949Q618691
    option: AES

